version: '3.8'

services:
  postgre:
    image: postgres
    container_name: currency-postgre
    environment:
       POSTGRES_PASSWORD: Unr4vel!
       POSTGRES_USER: Unravel
       POSTGRES_DB: currency-app-db
    ports:
      - 5432:5432
    volumes:
      - postgres-template-data:/var/lib/postgresql/data
    networks:
      - app-network

  # currency.app.api:
  #   container_name: currency.app.api
  #   build:
  #       context: .
  #       dockerfile: src/Presentation/API/Dockerfile
  #   restart: on-failure
  #   environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #       - "ConnectionStrings:PgSQL=Server=postgre;Port=5432;Database=currency-app-db;User Id=Unravel;Password=Unr4vel!;"
  #       - "Token:Audience=Unravel"
  #       - "Token:Issuer=Unravel"
  #       - "Token:SecurityKey=myubersuberprivatesecuritykey12345!Unr4vel!"
  #   ports:
  #       - 5275:8080
  #   depends_on:
  #       - postgre
  #   networks:
  #       - app-network

  # currency.app.mvc:
  #   container_name: currency.app.mvc
  #   build:
  #       context: .
  #       dockerfile: src/Presentation/Client/Dockerfile
  #   restart: on-failure
  #   environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #       - 5006:8081
  #   networks:
  #       - app-network
  
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: currency-app-redis
    environment:
        REDIS_PASSWORD: Unr4vel!
    command: redis-server --save 20 1 --loglevel warning --requirepass Unr4vel!
    ports:
      - "6379:6379"
    volumes:
      - reddit-data:/var/lib/redis/data
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-template-data:
  reddit-data: